//
//
//
#ifndef XHPTDC8_UTIL_H
#define XHPTDC8_UTIL_H

#include "xhptdc8_interface.h"

#ifdef __cplusplus
extern "C" {
#endif

	#if defined(_WIN32) || defined(_WIN64)
	#ifdef XHPTDC8_UTIL_EXPORTS
	#define XHPTDC8_UTIL_API __declspec(dllexport)
	#else
	#define XHPTDC8_UTIL_API __declspec(dllimport)
	#endif
	#else
	#define __int64 long long
	#define XHPTDC8_UTIL_API 
	#endif

	/// <summary>
	/// This functions applies all values provided in <paramref name="yaml_string"/> 
	/// on (overwrite) the corresponding memebers of <paramref name="manager_config"/>. 
	/// Members that are not referenced in yaml_string will be left unchanged in configs.
	/// </summary>
	/// <param name="manager_config">Initialized xhptdc8_manager_configuration object</param>  
	/// <param name="yaml_string">YAML string that has the values to be applied</param>  
	/// <returns>
	/// <para>+ve Numebr: count of device configuraions updated at success. <br/></para>
	/// <para>-ve Number: error code, XHPTDC8_INVALID_ARGUMENTS or one of the 
	/// "XHPTDC8_APPLY_YAML_" prefixed error codes defined in "xhptdc8_util.h".</para>
	/// </returns>
	XHPTDC8_UTIL_API int xhptdc8_apply_yaml(xhptdc8_manager_configuration* cfg, 
		const char* yaml_string);	

	// All Errors should be -ve 
	#define XHPTDC8_APPLY_YAML_INVALID_ARGUMENT			-01
	#define XHPTDC8_APPLY_YAML_ERR_NO_CONF_MNGR			-10
	#define XHPTDC8_APPLY_YAML_ERR_EMPTY_CONF_MNGR		-11
	#define XHPTDC8_APPLY_YAML_ERR_NO_DEV_CONFS			-20
	#define XHPTDC8_APPLY_YAML_ERR_EMPTY_DEV_CONFS		-21
	#define XHPTDC8_APPLY_YAML_ERR_CONFS_EXCEED_MAX		-22
	#define XHPTDC8_APPLY_YAML_ERR_INVALID_CONFS_STRUTC	-23
	#define XHPTDC8_APPLY_YAML_ERR_EMPTY_DEV_CONF		-31
	#define XHPTDC8_APPLY_YAML_INVALID_AUTO_TRIG_PRD	-32
	#define XHPTDC8_APPLY_YAML_INVALID_AUTO_TRIG_RAND	-33
	#define XHPTDC8_APPLY_YAML_INVALID_SKIP_ALGNMT		-34
	#define XHPTDC8_APPLY_YAML_INVALID_ALGNMT_SRCE		-35
	#define XHPTDC8_APPLY_YAML_THRESHOLDS_EXCEED_MAX	-40
	#define XHPTDC8_APPLY_YAML_INVALID_THRESHOLD		-41
	#define XHPTDC8_APPLY_YAML_INVALID_THRESHOLD_STRUCT	-42
	#define XHPTDC8_APPLY_YAML_INVALID_TRIGGERS_FALL	-51
	#define XHPTDC8_APPLY_YAML_INVALID_TRIGGERS_RISING	-52
	#define XHPTDC8_APPLY_YAML_INVALID_TRIGGERS_STRUCT	-53
	#define XHPTDC8_APPLY_YAML_ERR_TRIGGERS_EXCEED_MAX	-54
	#define XHPTDC8_APPLY_YAML_ERR_GATE_BLOCK_EXCEED_MAX	-60
	#define XHPTDC8_APPLY_YAML_GTBLCK_INVALID_MODE			-61
	#define XHPTDC8_APPLY_YAML_GTBLCK_INVALID_NEGATE		-62
	#define XHPTDC8_APPLY_YAML_GTBLCK_INVALID_RETRIG		-63
	#define XHPTDC8_APPLY_YAML_GTBLCK_INVALID_START			-64
	#define XHPTDC8_APPLY_YAML_GTBLCK_INVALID_STOP			-65
	#define XHPTDC8_APPLY_YAML_GTBLCK_STOP_B4_START			-66
	#define XHPTDC8_APPLY_YAML_GTBLCK_INVALID_SOURCES		-67
	#define XHPTDC8_APPLY_YAML_GTBLCK_INVALID_STRUCT		-68
	#define XHPTDC8_APPLY_YAML_ERR_CHANNELS_EXCEED_MAX	-70
	#define XHPTDC8_APPLY_YAML_INVALID_CHANNEL_ENABLE	-71
	#define XHPTDC8_APPLY_YAML_INVALID_CHANNEL_RISING	-72
	#define XHPTDC8_APPLY_YAML_INVALID_CHANNEL_STRUCT	-73
	#define XHPTDC8_APPLY_YAML_INVALID_ADC_CHANNEL_ENABLE	-80
	#define XHPTDC8_APPLY_YAML_INVALID_ADC_CHANNEL_WDRO		-81	// watchdog_readout
	#define XHPTDC8_APPLY_YAML_INVALID_ADC_CHANNEL_WDI		-82	// watchdog_interval
	#define XHPTDC8_APPLY_YAML_INVALID_ADC_CHANNEL_TRTHRESH	-83 // trigger_threshold
	#define XHPTDC8_APPLY_YAML_INVALID_GROUPING_ENABLED		-90
	#define XHPTDC8_APPLY_YAML_INVALID_GROUPING_TRIGCH		-91	// trigger_channel
	#define XHPTDC8_APPLY_YAML_INVALID_GROUPING_ZEROCH		-92	// zero_channel
	#define XHPTDC8_APPLY_YAML_INVALID_GROUPING_ZEROCHOFF	-93
	#define XHPTDC8_APPLY_YAML_INVALID_GROUPING_RNGST		-94
	#define XHPTDC8_APPLY_YAML_INVALID_GROUPING_TRIGDT		-95
	#define XHPTDC8_APPLY_YAML_INVALID_GROUPING_REQWINHIT	-96
	#define XHPTDC8_APPLY_YAML_INVALID_GROUPING_VETOMD		-97
	#define XHPTDC8_APPLY_YAML_INVALID_GROUPING_VETORZERO	-98
	#define XHPTDC8_APPLY_YAML_INVALID_GROUPING_RANGE_START	-99
	#define XHPTDC8_APPLY_YAML_INVALID_GROUPING_RANGE_STOP	-100
	#define XHPTDC8_APPLY_YAML_INVALID_GROUPING_WINDO_START	-101
	#define XHPTDC8_APPLY_YAML_INVALID_GROUPING_WINDO_STOP	-102
	#define XHPTDC8_APPLY_YAML_INVALID_GROUPING_VETO_START	-103
	#define XHPTDC8_APPLY_YAML_INVALID_GROUPING_VETO_STOP	-104
	#define XHPTDC8_APPLY_YAML_ERR_TGRBLCK_EXCEED_MAX	-120
	#define XHPTDC8_APPLY_YAML_TGRBLCK_INVALID_MODE		-121
	#define XHPTDC8_APPLY_YAML_TGRBLCK_INVALID_NEGATE	-121
	#define XHPTDC8_APPLY_YAML_TGRBLCK_INVALID_RETRIG	-123
	#define XHPTDC8_APPLY_YAML_TGRBLCK_INVALID_START	-124
	#define XHPTDC8_APPLY_YAML_TGRBLCK_INVALID_STOP		-125
	#define XHPTDC8_APPLY_YAML_TGRBLCK_STOP_B4_START	-126
	#define XHPTDC8_APPLY_YAML_TGRBLCK_INVALID_SOURCES	-127
	#define XHPTDC8_APPLY_YAML_TGRBLCK_INVALID_STRUCT	-128
	#define XHPTDC8_APPLY_YAML_TGRBLCK_INVALID_INDEX	-129

#ifdef __cplusplus
}
#endif

#endif
